### ISSUE TITLE
IndexOutOfBounds error

### ISSUE THREAD

**Issue by drmattyg** [drmattyg/KarProcess#1]
Running KarProcess:
./run.sh -m /Users/mgordon/Downloads/all_shook_up_karaoke_songs_NifterDotCom.kar -v src/test/resources/tommyboy.mp4 -o ~/test/foo1.mp4

Got:

java.lang.IndexOutOfBoundsException: Index: 51, Size: 51
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.drmattyg.nanokaraoke.video.KaraokeScreen.render(KaraokeScreen.java:94)
	at com.drmattyg.nanokaraoke.video.KaraokeScreenMediaTool.onVideoPicture(KaraokeScreenMediaTool.java:73)
	at com.xuggle.mediatool.AMediaToolMixin.onVideoPicture(AMediaToolMixin.java:166)
	at com.xuggle.mediatool.MediaToolAdapter.onVideoPicture(MediaToolAdapter.java:169)
	at com.drmattyg.nanokaraoke.video.Rescaler.onVideoPicture(Rescaler.java:44)
	at com.xuggle.mediatool.AMediaToolMixin.onVideoPicture(AMediaToolMixin.java:166)
	at com.xuggle.mediatool.MediaReader.dispatchVideoPicture(MediaReader.java:610)
	at com.xuggle.mediatool.MediaReader.decodeVideo(MediaReader.java:519)
	at com.xuggle.mediatool.MediaReader.readPacket(MediaReader.java:475)
	at com.drmattyg.nanokaraoke.video.MediaTools$VideoCutter.cutVideo(MediaTools.java:102)
	at com.drmattyg.nanokaraoke.convert.ProcessKar.generateKarVideo(ProcessKar.java:50)
	at com.drmattyg.nanokaraoke.convert.ProcessKarCli.main(ProcessKarCli.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:313)
	at com.simontuffs.onejar.Boot.main(Boot.java:161)

**Comment by drmattyg** [comment]
Fixed
